// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/assets_generator
// **************************************************************************
class Resources {
  const Resources._();
  static const String assetsCaptchaHtml = 'assets/captcha.html';

  static const String assetsIconsMacosAppIconPng =
      'assets/icons/macos_app_icon.png';

  static const String assetsIconsWindowsAppIconPng =
      'assets/icons/windows_app_icon.png';

  static const String assetsImagesAboutLogoPng = 'assets/images/about_logo.png';

  static const String assetsImagesAppButtonSvg = 'assets/images/app_button.svg';

  static const String assetsImagesAttachmentDownloadSvg =
      'assets/images/attachment_download.svg';

  static const String assetsImagesAudioSvg = 'assets/images/audio.svg';

  static const String assetsImagesAudioPlaySvg = 'assets/images/audio_play.svg';

  static const String assetsImagesAudioStopSvg = 'assets/images/audio_stop.svg';

  static const String assetsImagesBotSvg = 'assets/images/bot.svg';

  static const String assetsImagesBotFillSvg = 'assets/images/bot_fill.svg';

  static const String assetsImagesChatSvg = 'assets/images/chat.svg';

  static const String assetsImagesChatBackgroundPng =
      'assets/images/chat_background.png';

  static const String assetsImagesChatBackupSvg =
      'assets/images/chat_backup.svg';

  static const String assetsImagesChatPinSvg = 'assets/images/chat_pin.svg';

  static const String assetsImagesChatSmallSvg = 'assets/images/chat_small.svg';

  static const String assetsImagesCheckedSvg = 'assets/images/checked.svg';

  static const String assetsImagesCircleSvg = 'assets/images/circle.svg';

  static const String assetsImagesCircleAddSvg = 'assets/images/circle_add.svg';

  static const String assetsImagesCircleRemoveSvg =
      'assets/images/circle_remove.svg';

  static const String assetsImagesCloseOvalSvg = 'assets/images/close_oval.svg';

  static const String assetsImagesCollapseSvg = 'assets/images/collapse.svg';

  static const String assetsImagesContactSvg = 'assets/images/contact.svg';

  static const String assetsImagesContextMenuChatSvg =
      'assets/images/context_menu_chat.svg';

  static const String assetsImagesContextMenuCopySvg =
      'assets/images/context_menu_copy.svg';

  static const String assetsImagesContextMenuCreateConversationSvg =
      'assets/images/context_menu_create_conversation.svg';

  static const String assetsImagesContextMenuCreateGroupSvg =
      'assets/images/context_menu_create_group.svg';

  static const String assetsImagesContextMenuDeleteSvg =
      'assets/images/context_menu_delete.svg';

  static const String assetsImagesContextMenuDownloadSvg =
      'assets/images/context_menu_download.svg';

  static const String assetsImagesContextMenuEditSvg =
      'assets/images/context_menu_edit.svg';

  static const String assetsImagesContextMenuEditCircleSvg =
      'assets/images/context_menu_edit_circle.svg';

  static const String assetsImagesContextMenuForwardSvg =
      'assets/images/context_menu_forward.svg';

  static const String assetsImagesContextMenuGotoSvg =
      'assets/images/context_menu_goto.svg';

  static const String assetsImagesContextMenuLinkSvg =
      'assets/images/context_menu_link.svg';

  static const String assetsImagesContextMenuMuteSvg =
      'assets/images/context_menu_mute.svg';

  static const String assetsImagesContextMenuPinSvg =
      'assets/images/context_menu_pin.svg';

  static const String assetsImagesContextMenuRecallSvg =
      'assets/images/context_menu_recall.svg';

  static const String assetsImagesContextMenuReplySvg =
      'assets/images/context_menu_reply.svg';

  static const String assetsImagesContextMenuSearchUserSvg =
      'assets/images/context_menu_search_user.svg';

  static const String assetsImagesContextMenuStickerSvg =
      'assets/images/context_menu_sticker.svg';

  static const String assetsImagesContextMenuStopSvg =
      'assets/images/context_menu_stop.svg';

  static const String assetsImagesContextMenuUnmuteSvg =
      'assets/images/context_menu_unmute.svg';

  static const String assetsImagesContextMenuUnpinSvg =
      'assets/images/context_menu_unpin.svg';

  static const String assetsImagesContextMenuUserEditSvg =
      'assets/images/context_menu_user_edit.svg';

  static const String assetsImagesCopySvg = 'assets/images/copy.svg';

  static const String assetsImagesDeleteSvg = 'assets/images/delete.svg';

  static const String assetsImagesDeliveredSvg = 'assets/images/delivered.svg';

  static const String assetsImagesDisappearingMessageSvg =
      'assets/images/disappearing_message.svg';

  static const String assetsImagesDownloadSvg = 'assets/images/download.svg';

  static const String assetsImagesEditImageSvg = 'assets/images/edit_image.svg';

  static const String assetsImagesEditImageClipSvg =
      'assets/images/edit_image_clip.svg';

  static const String assetsImagesEditImageDrawSvg =
      'assets/images/edit_image_draw.svg';

  static const String assetsImagesEditImageEraseSvg =
      'assets/images/edit_image_erase.svg';

  static const String assetsImagesEditImageFlipSvg =
      'assets/images/edit_image_flip.svg';

  static const String assetsImagesEditImageRedoSvg =
      'assets/images/edit_image_redo.svg';

  static const String assetsImagesEditImageRotateSvg =
      'assets/images/edit_image_rotate.svg';

  static const String assetsImagesEditImageUndoSvg =
      'assets/images/edit_image_undo.svg';

  static const String assetsImagesEmojiAnimalSvg =
      'assets/images/emoji_animal.svg';

  static const String assetsImagesEmojiFaceSvg = 'assets/images/emoji_face.svg';

  static const String assetsImagesEmojiFlagsSvg =
      'assets/images/emoji_flags.svg';

  static const String assetsImagesEmojiFoodSvg = 'assets/images/emoji_food.svg';

  static const String assetsImagesEmojiObjectsSvg =
      'assets/images/emoji_objects.svg';

  static const String assetsImagesEmojiRecentSvg =
      'assets/images/emoji_recent.svg';

  static const String assetsImagesEmojiSportsSvg =
      'assets/images/emoji_sports.svg';

  static const String assetsImagesEmojiStickerSvg =
      'assets/images/emoji_sticker.svg';

  static const String assetsImagesEmojiSymbolSvg =
      'assets/images/emoji_symbol.svg';

  static const String assetsImagesEmojiTravelSvg =
      'assets/images/emoji_travel.svg';

  static const String assetsImagesEmptyFileSvg = 'assets/images/empty_file.svg';

  static const String assetsImagesEmptyImageSvg =
      'assets/images/empty_image.svg';

  static const String assetsImagesExclamationMarkSvg =
      'assets/images/exclamation_mark.svg';

  static const String assetsImagesExpandedSvg = 'assets/images/expanded.svg';

  static const String assetsImagesExpiringSvg = 'assets/images/expiring.svg';

  static const String assetsImagesExpiringDarkSvg =
      'assets/images/expiring_dark.svg';

  static const String assetsImagesFailedSvg = 'assets/images/failed.svg';

  static const String assetsImagesFileSvg = 'assets/images/file.svg';

  static const String assetsImagesFilePreviewFilesSvg =
      'assets/images/file_preview_files.svg';

  static const String assetsImagesFilePreviewImagesSvg =
      'assets/images/file_preview_images.svg';

  static const String assetsImagesFilePreviewZipSvg =
      'assets/images/file_preview_zip.svg';

  static const String assetsImagesGifStickerSvg =
      'assets/images/gif_sticker.svg';

  static const String assetsImagesGroupSvg = 'assets/images/group.svg';

  static const String assetsImagesIcAboutSvg = 'assets/images/ic_about.svg';

  static const String assetsImagesIcAddSvg = 'assets/images/ic_add.svg';

  static const String assetsImagesIcAppearanceSvg =
      'assets/images/ic_appearance.svg';

  static const String assetsImagesIcArrowRightSvg =
      'assets/images/ic_arrow_right.svg';

  static const String assetsImagesIcBackSvg = 'assets/images/ic_back.svg';

  static const String assetsImagesIcBackupSvg = 'assets/images/ic_backup.svg';

  static const String assetsImagesIcCloseSvg = 'assets/images/ic_close.svg';

  static const String assetsImagesIcCloseBigSvg =
      'assets/images/ic_close_big.svg';

  static const String assetsImagesIcFileSvg = 'assets/images/ic_file.svg';

  static const String assetsImagesIcForwardSvg = 'assets/images/ic_forward.svg';

  static const String assetsImagesIcNotificationSvg =
      'assets/images/ic_notification.svg';

  static const String assetsImagesIcProfileSvg = 'assets/images/ic_profile.svg';

  static const String assetsImagesIcRetrySvg = 'assets/images/ic_retry.svg';

  static const String assetsImagesIcScreenSvg = 'assets/images/ic_screen.svg';

  static const String assetsImagesIcSearchSvg = 'assets/images/ic_search.svg';

  static const String assetsImagesIcSearchSmallSvg =
      'assets/images/ic_search_small.svg';

  static const String assetsImagesIcSendSvg = 'assets/images/ic_send.svg';

  static const String assetsImagesIcSignOutSvg =
      'assets/images/ic_sign_out.svg';

  static const String assetsImagesIcStickerSvg = 'assets/images/ic_sticker.svg';

  static const String assetsImagesIcStorageUsageSvg =
      'assets/images/ic_storage_usage.svg';

  static const String assetsImagesImageSvg = 'assets/images/image.svg';

  static const String assetsImagesInformationSvg =
      'assets/images/information.svg';

  static const String assetsImagesInviteCopySvg =
      'assets/images/invite_copy.svg';

  static const String assetsImagesInviteRefreshSvg =
      'assets/images/invite_refresh.svg';

  static const String assetsImagesInviteShareSvg =
      'assets/images/invite_share.svg';

  static const String assetsImagesJumpCurrentArrowSvg =
      'assets/images/jump_current_arrow.svg';

  static const String assetsImagesLightReceiverNipBubblePng =
      'assets/images/light_receiver_nip_bubble.png';

  static const String assetsImagesLightSenderNipBubblePng =
      'assets/images/light_sender_nip_bubble.png';

  static const String assetsImagesLiveSvg = 'assets/images/live.svg';

  static const String assetsImagesLocationSvg = 'assets/images/location.svg';

  static const String assetsImagesLocationMarkSvg =
      'assets/images/location_mark.svg';

  static const String assetsImagesLogoPng = 'assets/images/logo.png';

  static const String assetsImagesMessagePinSvg =
      'assets/images/message_pin.svg';

  static const String assetsImagesMessageRepresentativeSvg =
      'assets/images/message_representative.svg';

  static const String assetsImagesMessageSecretSvg =
      'assets/images/message_secret.svg';

  static const String assetsImagesMessageTranscriptForwardSvg =
      'assets/images/message_transcript_forward.svg';

  static const String assetsImagesMultiSelectionSvg =
      'assets/images/multi_selection.svg';

  static const String assetsImagesMuteSvg = 'assets/images/mute.svg';

  static const String assetsImagesNextSvg = 'assets/images/next.svg';

  static const String assetsImagesNoResultSvg = 'assets/images/no_result.svg';

  static const String assetsImagesNotifyIconIco =
      'assets/images/notify_icon.ico';

  static const String assetsImagesPersonalStickerSvg =
      'assets/images/personal_sticker.svg';

  static const String assetsImagesPinSvg = 'assets/images/pin.svg';

  static const String assetsImagesPinArrowSvg = 'assets/images/pin_arrow.svg';

  static const String assetsImagesPlaySvg = 'assets/images/play.svg';

  static const String assetsImagesPostDetailSvg =
      'assets/images/post_detail.svg';

  static const String assetsImagesPrevSvg = 'assets/images/prev.svg';

  static const String assetsImagesReadSvg = 'assets/images/read.svg';

  static const String assetsImagesRecallSvg = 'assets/images/recall.svg';

  static const String assetsImagesRecentStickerSvg =
      'assets/images/recent_sticker.svg';

  static const String assetsImagesRotatoSvg = 'assets/images/rotato.svg';

  static const String assetsImagesSelectedSvg = 'assets/images/selected.svg';

  static const String assetsImagesSentSvg = 'assets/images/sent.svg';

  static const String assetsImagesSettingSvg = 'assets/images/setting.svg';

  static const String assetsImagesShareSvg = 'assets/images/share.svg';

  static const String assetsImagesSlideContactsSvg =
      'assets/images/slide_contacts.svg';

  static const String assetsImagesSmallCloseSvg =
      'assets/images/small_close.svg';

  static const String assetsImagesStickerSvg = 'assets/images/sticker.svg';

  static const String assetsImagesStickerStoreSvg =
      'assets/images/sticker_store.svg';

  static const String assetsImagesStickerStoreRedDotSvg =
      'assets/images/sticker_store_red_dot.svg';

  static const String assetsImagesStrangersSvg = 'assets/images/strangers.svg';

  static const String assetsImagesSuccessfulSvg =
      'assets/images/successful.svg';

  static const String assetsImagesTransferSvg = 'assets/images/transfer.svg';

  static const String assetsImagesTriangleWarningSvg =
      'assets/images/triangle_warning.svg';

  static const String assetsImagesUploadSvg = 'assets/images/upload.svg';

  static const String assetsImagesUserSearchSvg =
      'assets/images/user_search.svg';

  static const String assetsImagesVerifiedSvg = 'assets/images/verified.svg';

  static const String assetsImagesVideoSvg = 'assets/images/video.svg';

  static const String assetsImagesVideoCallSvg = 'assets/images/video_call.svg';

  static const String assetsImagesVideoMessageSvg =
      'assets/images/video_message.svg';

  static const String assetsImagesWarningSvg = 'assets/images/warning.svg';

  static const String assetsImagesWebViewRefreshSvg =
      'assets/images/web_view_refresh.svg';

  static const String assetsImagesZoomInSvg = 'assets/images/zoom_in.svg';

  static const String assetsImagesZoomOutSvg = 'assets/images/zoom_out.svg';
}
