// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/assets_generator
// **************************************************************************
class Resources {
  const Resources._();
  static const String assetsImagesAppButtonSvg = 'assets/images/app_button.svg';

  static const String assetsImagesAttachmentDownloadSvg =
      'assets/images/attachment_download.svg';

  static const String assetsImagesAudioSvg = 'assets/images/audio.svg';

  static const String assetsImagesBotPng = 'assets/images/bot.png';

  static const String assetsImagesBotFillSvg = 'assets/images/bot_fill.svg';

  static const String assetsImagesCirclePng = 'assets/images/circle.png';

  static const String assetsImagesContactSvg = 'assets/images/contact.svg';

  static const String assetsImagesContactsPng = 'assets/images/contacts.png';

  static const String assetsImagesConversationEmptySvg =
      'assets/images/conversation_empty.svg';

  static const String assetsImagesCopySvg = 'assets/images/copy.svg';

  static const String assetsImagesDarkReceiverNipBubblePng =
      'assets/images/dark_receiver_nip_bubble.png';

  static const String assetsImagesDarkSenderNipBubblePng =
      'assets/images/dark_sender_nip_bubble.png';

  static const String assetsImagesDeliveredSvg = 'assets/images/delivered.svg';

  static const String assetsImagesDownloadSvg = 'assets/images/download.svg';

  static const String assetsImagesFileSvg = 'assets/images/file.svg';

  static const String assetsImagesGifStickerSvg =
      'assets/images/gif_sticker.svg';

  static const String assetsImagesGroupPng = 'assets/images/group.png';

  static const String assetsImagesIcAboutSvg = 'assets/images/ic_about.svg';

  static const String assetsImagesIcAppearanceSvg =
      'assets/images/ic_appearance.svg';

  static const String assetsImagesIcArrowRightSvg =
      'assets/images/ic_arrow_right.svg';

  static const String assetsImagesIcBackSvg = 'assets/images/ic_back.svg';

  static const String assetsImagesIcBackupSvg = 'assets/images/ic_backup.svg';

  static const String assetsImagesIcCloseSvg = 'assets/images/ic_close.svg';

  static const String assetsImagesIcCreateSvg = 'assets/images/ic_create.svg';

  static const String assetsImagesIcFileSvg = 'assets/images/ic_file.svg';

  static const String assetsImagesIcNotificationSvg =
      'assets/images/ic_notification.svg';

  static const String assetsImagesIcProfileSvg = 'assets/images/ic_profile.svg';

  static const String assetsImagesIcRetrySvg = 'assets/images/ic_retry.svg';

  static const String assetsImagesIcScreenSvg = 'assets/images/ic_screen.svg';

  static const String assetsImagesIcSearchSvg = 'assets/images/ic_search.svg';

  static const String assetsImagesIcSendSvg = 'assets/images/ic_send.svg';

  static const String assetsImagesIcSignOutSvg =
      'assets/images/ic_sign_out.svg';

  static const String assetsImagesIcStickerSvg = 'assets/images/ic_sticker.svg';

  static const String assetsImagesIcStorageUsageSvg =
      'assets/images/ic_storage_usage.svg';

  static const String assetsImagesImageSvg = 'assets/images/image.svg';

  static const String assetsImagesLightReceiverNipBubblePng =
      'assets/images/light_receiver_nip_bubble.png';

  static const String assetsImagesLightSenderNipBubblePng =
      'assets/images/light_sender_nip_bubble.png';

  static const String assetsImagesLiveSvg = 'assets/images/live.svg';

  static const String assetsImagesLogoPng = 'assets/images/logo.png';

  static const String assetsImagesMuteSvg = 'assets/images/mute.svg';

  static const String assetsImagesNextSvg = 'assets/images/next.svg';

  static const String assetsImagesPersonalStickerSvg =
      'assets/images/personal_sticker.svg';

  static const String assetsImagesPinSvg = 'assets/images/pin.svg';

  static const String assetsImagesPlaySvg = 'assets/images/play.svg';

  static const String assetsImagesPrevSvg = 'assets/images/prev.svg';

  static const String assetsImagesReadSvg = 'assets/images/read.svg';

  static const String assetsImagesRecallSvg = 'assets/images/recall.svg';

  static const String assetsImagesRecentStickerSvg =
      'assets/images/recent_sticker.svg';

  static const String assetsImagesSendingSvg = 'assets/images/sending.svg';

  static const String assetsImagesSentSvg = 'assets/images/sent.svg';

  static const String assetsImagesShareSvg = 'assets/images/share.svg';

  static const String assetsImagesStickerSvg = 'assets/images/sticker.svg';

  static const String assetsImagesStrangersPng = 'assets/images/strangers.png';

  static const String assetsImagesTransferSvg = 'assets/images/transfer.svg';

  static const String assetsImagesUploadSvg = 'assets/images/upload.svg';

  static const String assetsImagesVerifiedSvg = 'assets/images/verified.svg';

  static const String assetsImagesVideoSvg = 'assets/images/video.svg';

  static const String assetsImagesVideoCallSvg = 'assets/images/video_call.svg';

  static const String assetsImagesWarningSvg = 'assets/images/warning.svg';

  static const String assetsImagesZoomInSvg = 'assets/images/zoom_in.svg';

  static const String assetsImagesZoomOutSvg = 'assets/images/zoom_out.svg';
}
