// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/assets_generator
// **************************************************************************
// ignore_for_file: constant_identifier_names

class Resources {
  const Resources._();
  static const String assetsCaptchaHtml = 'assets/captcha.html';

  static const String assetsFontsIconfontTtf = 'assets/fonts/iconfont.ttf';

  /// {@macro assets_generator.assetsIconsMacosAppIconPng.preview}
  static const String assetsIconsMacosAppIconPng =
      'assets/icons/macos_app_icon.png';

  /// {@macro assets_generator.assetsIconsWindowsAppIconPng.preview}
  static const String assetsIconsWindowsAppIconPng =
      'assets/icons/windows_app_icon.png';

  /// {@macro assets_generator.assetsImagesAboutLogoPng.preview}
  static const String assetsImagesAboutLogoPng = 'assets/images/about_logo.png';

  /// {@macro assets_generator.assetsImagesAccountSvg.preview}
  static const String assetsImagesAccountSvg = 'assets/images/account.svg';

  /// {@macro assets_generator.assetsImagesAddStickerSvg.preview}
  static const String assetsImagesAddStickerSvg =
      'assets/images/add_sticker.svg';

  /// {@macro assets_generator.assetsImagesAppButtonSvg.preview}
  static const String assetsImagesAppButtonSvg = 'assets/images/app_button.svg';

  /// {@macro assets_generator.assetsImagesAttachmentDownloadSvg.preview}
  static const String assetsImagesAttachmentDownloadSvg =
      'assets/images/attachment_download.svg';

  /// {@macro assets_generator.assetsImagesAudioSvg.preview}
  static const String assetsImagesAudioSvg = 'assets/images/audio.svg';

  /// {@macro assets_generator.assetsImagesAudioPlaySvg.preview}
  static const String assetsImagesAudioPlaySvg = 'assets/images/audio_play.svg';

  /// {@macro assets_generator.assetsImagesAudioStopSvg.preview}
  static const String assetsImagesAudioStopSvg = 'assets/images/audio_stop.svg';

  /// {@macro assets_generator.assetsImagesBgSnapshotSvg.preview}
  static const String assetsImagesBgSnapshotSvg =
      'assets/images/bg_snapshot.svg';

  /// {@macro assets_generator.assetsImagesBotSvg.preview}
  static const String assetsImagesBotSvg = 'assets/images/bot.svg';

  /// {@macro assets_generator.assetsImagesBotFillSvg.preview}
  static const String assetsImagesBotFillSvg = 'assets/images/bot_fill.svg';

  /// {@macro assets_generator.assetsImagesChatSvg.preview}
  static const String assetsImagesChatSvg = 'assets/images/chat.svg';

  /// {@macro assets_generator.assetsImagesChatBackgroundPng.preview}
  static const String assetsImagesChatBackgroundPng =
      'assets/images/chat_background.png';

  /// {@macro assets_generator.assetsImagesChatBackupSvg.preview}
  static const String assetsImagesChatBackupSvg =
      'assets/images/chat_backup.svg';

  /// {@macro assets_generator.assetsImagesChatPinSvg.preview}
  static const String assetsImagesChatPinSvg = 'assets/images/chat_pin.svg';

  /// {@macro assets_generator.assetsImagesChatSmallSvg.preview}
  static const String assetsImagesChatSmallSvg = 'assets/images/chat_small.svg';

  /// {@macro assets_generator.assetsImagesCheckedSvg.preview}
  static const String assetsImagesCheckedSvg = 'assets/images/checked.svg';

  /// {@macro assets_generator.assetsImagesCircleSvg.preview}
  static const String assetsImagesCircleSvg = 'assets/images/circle.svg';

  /// {@macro assets_generator.assetsImagesCircleAddSvg.preview}
  static const String assetsImagesCircleAddSvg = 'assets/images/circle_add.svg';

  /// {@macro assets_generator.assetsImagesCircleRemoveSvg.preview}
  static const String assetsImagesCircleRemoveSvg =
      'assets/images/circle_remove.svg';

  /// {@macro assets_generator.assetsImagesCloseOvalSvg.preview}
  static const String assetsImagesCloseOvalSvg = 'assets/images/close_oval.svg';

  /// {@macro assets_generator.assetsImagesCloseOvalRecordSvg.preview}
  static const String assetsImagesCloseOvalRecordSvg =
      'assets/images/close_oval_record.svg';

  /// {@macro assets_generator.assetsImagesCollapseSvg.preview}
  static const String assetsImagesCollapseSvg = 'assets/images/collapse.svg';

  /// {@macro assets_generator.assetsImagesContactSvg.preview}
  static const String assetsImagesContactSvg = 'assets/images/contact.svg';

  /// {@macro assets_generator.assetsImagesContextMenuCopySvg.preview}
  static const String assetsImagesContextMenuCopySvg =
      'assets/images/context_menu_copy.svg';

  /// {@macro assets_generator.assetsImagesContextMenuCreateConversationSvg.preview}
  static const String assetsImagesContextMenuCreateConversationSvg =
      'assets/images/context_menu_create_conversation.svg';

  /// {@macro assets_generator.assetsImagesContextMenuCreateGroupSvg.preview}
  static const String assetsImagesContextMenuCreateGroupSvg =
      'assets/images/context_menu_create_group.svg';

  /// {@macro assets_generator.assetsImagesContextMenuDeleteSvg.preview}
  static const String assetsImagesContextMenuDeleteSvg =
      'assets/images/context_menu_delete.svg';

  /// {@macro assets_generator.assetsImagesContextMenuForwardSvg.preview}
  static const String assetsImagesContextMenuForwardSvg =
      'assets/images/context_menu_forward.svg';

  /// {@macro assets_generator.assetsImagesContextMenuLinkSvg.preview}
  static const String assetsImagesContextMenuLinkSvg =
      'assets/images/context_menu_link.svg';

  /// {@macro assets_generator.assetsImagesContextMenuSearchUserSvg.preview}
  static const String assetsImagesContextMenuSearchUserSvg =
      'assets/images/context_menu_search_user.svg';

  /// {@macro assets_generator.assetsImagesCopySvg.preview}
  static const String assetsImagesCopySvg = 'assets/images/copy.svg';

  /// {@macro assets_generator.assetsImagesDeleteSvg.preview}
  static const String assetsImagesDeleteSvg = 'assets/images/delete.svg';

  /// {@macro assets_generator.assetsImagesDeleteAccountSvg.preview}
  static const String assetsImagesDeleteAccountSvg =
      'assets/images/delete_account.svg';

  /// {@macro assets_generator.assetsImagesDeliveredSvg.preview}
  static const String assetsImagesDeliveredSvg = 'assets/images/delivered.svg';

  /// {@macro assets_generator.assetsImagesDeviceTransferSvg.preview}
  static const String assetsImagesDeviceTransferSvg =
      'assets/images/device_transfer.svg';

  /// {@macro assets_generator.assetsImagesDisappearingMessageSvg.preview}
  static const String assetsImagesDisappearingMessageSvg =
      'assets/images/disappearing_message.svg';

  /// {@macro assets_generator.assetsImagesDownloadSvg.preview}
  static const String assetsImagesDownloadSvg = 'assets/images/download.svg';

  /// {@macro assets_generator.assetsImagesEditImageSvg.preview}
  static const String assetsImagesEditImageSvg = 'assets/images/edit_image.svg';

  /// {@macro assets_generator.assetsImagesEditImageClipSvg.preview}
  static const String assetsImagesEditImageClipSvg =
      'assets/images/edit_image_clip.svg';

  /// {@macro assets_generator.assetsImagesEditImageDrawSvg.preview}
  static const String assetsImagesEditImageDrawSvg =
      'assets/images/edit_image_draw.svg';

  /// {@macro assets_generator.assetsImagesEditImageEraseSvg.preview}
  static const String assetsImagesEditImageEraseSvg =
      'assets/images/edit_image_erase.svg';

  /// {@macro assets_generator.assetsImagesEditImageFlipSvg.preview}
  static const String assetsImagesEditImageFlipSvg =
      'assets/images/edit_image_flip.svg';

  /// {@macro assets_generator.assetsImagesEditImageRedoSvg.preview}
  static const String assetsImagesEditImageRedoSvg =
      'assets/images/edit_image_redo.svg';

  /// {@macro assets_generator.assetsImagesEditImageRotateSvg.preview}
  static const String assetsImagesEditImageRotateSvg =
      'assets/images/edit_image_rotate.svg';

  /// {@macro assets_generator.assetsImagesEditImageUndoSvg.preview}
  static const String assetsImagesEditImageUndoSvg =
      'assets/images/edit_image_undo.svg';

  /// {@macro assets_generator.assetsImagesEllipsisSvg.preview}
  static const String assetsImagesEllipsisSvg = 'assets/images/ellipsis.svg';

  /// {@macro assets_generator.assetsImagesEmojiAnimalSvg.preview}
  static const String assetsImagesEmojiAnimalSvg =
      'assets/images/emoji_animal.svg';

  /// {@macro assets_generator.assetsImagesEmojiFaceSvg.preview}
  static const String assetsImagesEmojiFaceSvg = 'assets/images/emoji_face.svg';

  /// {@macro assets_generator.assetsImagesEmojiFlagsSvg.preview}
  static const String assetsImagesEmojiFlagsSvg =
      'assets/images/emoji_flags.svg';

  /// {@macro assets_generator.assetsImagesEmojiFoodSvg.preview}
  static const String assetsImagesEmojiFoodSvg = 'assets/images/emoji_food.svg';

  /// {@macro assets_generator.assetsImagesEmojiObjectsSvg.preview}
  static const String assetsImagesEmojiObjectsSvg =
      'assets/images/emoji_objects.svg';

  /// {@macro assets_generator.assetsImagesEmojiRecentSvg.preview}
  static const String assetsImagesEmojiRecentSvg =
      'assets/images/emoji_recent.svg';

  /// {@macro assets_generator.assetsImagesEmojiSportsSvg.preview}
  static const String assetsImagesEmojiSportsSvg =
      'assets/images/emoji_sports.svg';

  /// {@macro assets_generator.assetsImagesEmojiStickerSvg.preview}
  static const String assetsImagesEmojiStickerSvg =
      'assets/images/emoji_sticker.svg';

  /// {@macro assets_generator.assetsImagesEmojiSymbolSvg.preview}
  static const String assetsImagesEmojiSymbolSvg =
      'assets/images/emoji_symbol.svg';

  /// {@macro assets_generator.assetsImagesEmojiTravelSvg.preview}
  static const String assetsImagesEmojiTravelSvg =
      'assets/images/emoji_travel.svg';

  /// {@macro assets_generator.assetsImagesEmptyFileSvg.preview}
  static const String assetsImagesEmptyFileSvg = 'assets/images/empty_file.svg';

  /// {@macro assets_generator.assetsImagesEmptyImageSvg.preview}
  static const String assetsImagesEmptyImageSvg =
      'assets/images/empty_image.svg';

  /// {@macro assets_generator.assetsImagesExclamationMarkSvg.preview}
  static const String assetsImagesExclamationMarkSvg =
      'assets/images/exclamation_mark.svg';

  /// {@macro assets_generator.assetsImagesExpandedSvg.preview}
  static const String assetsImagesExpandedSvg = 'assets/images/expanded.svg';

  /// {@macro assets_generator.assetsImagesExpiringSvg.preview}
  static const String assetsImagesExpiringSvg = 'assets/images/expiring.svg';

  /// {@macro assets_generator.assetsImagesExpiringDarkSvg.preview}
  static const String assetsImagesExpiringDarkSvg =
      'assets/images/expiring_dark.svg';

  /// {@macro assets_generator.assetsImagesFailedSvg.preview}
  static const String assetsImagesFailedSvg = 'assets/images/failed.svg';

  /// {@macro assets_generator.assetsImagesFileSvg.preview}
  static const String assetsImagesFileSvg = 'assets/images/file.svg';

  /// {@macro assets_generator.assetsImagesFilePreviewFilesSvg.preview}
  static const String assetsImagesFilePreviewFilesSvg =
      'assets/images/file_preview_files.svg';

  /// {@macro assets_generator.assetsImagesFilePreviewImagesSvg.preview}
  static const String assetsImagesFilePreviewImagesSvg =
      'assets/images/file_preview_images.svg';

  /// {@macro assets_generator.assetsImagesFilePreviewZipSvg.preview}
  static const String assetsImagesFilePreviewZipSvg =
      'assets/images/file_preview_zip.svg';

  /// {@macro assets_generator.assetsImagesFilterUnseenSvg.preview}
  static const String assetsImagesFilterUnseenSvg =
      'assets/images/filter_unseen.svg';

  /// {@macro assets_generator.assetsImagesGifStickerSvg.preview}
  static const String assetsImagesGifStickerSvg =
      'assets/images/gif_sticker.svg';

  /// {@macro assets_generator.assetsImagesGroupSvg.preview}
  static const String assetsImagesGroupSvg = 'assets/images/group.svg';

  /// {@macro assets_generator.assetsImagesIcAboutSvg.preview}
  static const String assetsImagesIcAboutSvg = 'assets/images/ic_about.svg';

  /// {@macro assets_generator.assetsImagesIcAddSvg.preview}
  static const String assetsImagesIcAddSvg = 'assets/images/ic_add.svg';

  /// {@macro assets_generator.assetsImagesIcAppearanceSvg.preview}
  static const String assetsImagesIcAppearanceSvg =
      'assets/images/ic_appearance.svg';

  /// {@macro assets_generator.assetsImagesIcArrowRightSvg.preview}
  static const String assetsImagesIcArrowRightSvg =
      'assets/images/ic_arrow_right.svg';

  /// {@macro assets_generator.assetsImagesIcBackSvg.preview}
  static const String assetsImagesIcBackSvg = 'assets/images/ic_back.svg';

  /// {@macro assets_generator.assetsImagesIcBackupSvg.preview}
  static const String assetsImagesIcBackupSvg = 'assets/images/ic_backup.svg';

  /// {@macro assets_generator.assetsImagesIcCloseSvg.preview}
  static const String assetsImagesIcCloseSvg = 'assets/images/ic_close.svg';

  /// {@macro assets_generator.assetsImagesIcCloseBigSvg.preview}
  static const String assetsImagesIcCloseBigSvg =
      'assets/images/ic_close_big.svg';

  /// {@macro assets_generator.assetsImagesIcFileSvg.preview}
  static const String assetsImagesIcFileSvg = 'assets/images/ic_file.svg';

  /// {@macro assets_generator.assetsImagesIcForwardSvg.preview}
  static const String assetsImagesIcForwardSvg = 'assets/images/ic_forward.svg';

  /// {@macro assets_generator.assetsImagesIcNotificationSvg.preview}
  static const String assetsImagesIcNotificationSvg =
      'assets/images/ic_notification.svg';

  /// {@macro assets_generator.assetsImagesIcProfileSvg.preview}
  static const String assetsImagesIcProfileSvg = 'assets/images/ic_profile.svg';

  /// {@macro assets_generator.assetsImagesIcRetrySvg.preview}
  static const String assetsImagesIcRetrySvg = 'assets/images/ic_retry.svg';

  /// {@macro assets_generator.assetsImagesIcScreenSvg.preview}
  static const String assetsImagesIcScreenSvg = 'assets/images/ic_screen.svg';

  /// {@macro assets_generator.assetsImagesIcSearchSvg.preview}
  static const String assetsImagesIcSearchSvg = 'assets/images/ic_search.svg';

  /// {@macro assets_generator.assetsImagesIcSearchSmallSvg.preview}
  static const String assetsImagesIcSearchSmallSvg =
      'assets/images/ic_search_small.svg';

  /// {@macro assets_generator.assetsImagesIcSendSvg.preview}
  static const String assetsImagesIcSendSvg = 'assets/images/ic_send.svg';

  /// {@macro assets_generator.assetsImagesIcSignOutSvg.preview}
  static const String assetsImagesIcSignOutSvg =
      'assets/images/ic_sign_out.svg';

  /// {@macro assets_generator.assetsImagesIcStickerSvg.preview}
  static const String assetsImagesIcStickerSvg = 'assets/images/ic_sticker.svg';

  /// {@macro assets_generator.assetsImagesIcStorageUsageSvg.preview}
  static const String assetsImagesIcStorageUsageSvg =
      'assets/images/ic_storage_usage.svg';

  /// {@macro assets_generator.assetsImagesImageSvg.preview}
  static const String assetsImagesImageSvg = 'assets/images/image.svg';

  /// {@macro assets_generator.assetsImagesInformationSvg.preview}
  static const String assetsImagesInformationSvg =
      'assets/images/information.svg';

  /// {@macro assets_generator.assetsImagesInviteCopySvg.preview}
  static const String assetsImagesInviteCopySvg =
      'assets/images/invite_copy.svg';

  /// {@macro assets_generator.assetsImagesInviteRefreshSvg.preview}
  static const String assetsImagesInviteRefreshSvg =
      'assets/images/invite_refresh.svg';

  /// {@macro assets_generator.assetsImagesInviteShareSvg.preview}
  static const String assetsImagesInviteShareSvg =
      'assets/images/invite_share.svg';

  /// {@macro assets_generator.assetsImagesJumpCurrentArrowSvg.preview}
  static const String assetsImagesJumpCurrentArrowSvg =
      'assets/images/jump_current_arrow.svg';

  /// {@macro assets_generator.assetsImagesLightReceiverNipBubblePng.preview}
  static const String assetsImagesLightReceiverNipBubblePng =
      'assets/images/light_receiver_nip_bubble.png';

  /// {@macro assets_generator.assetsImagesLightSenderNipBubblePng.preview}
  static const String assetsImagesLightSenderNipBubblePng =
      'assets/images/light_sender_nip_bubble.png';

  /// {@macro assets_generator.assetsImagesLiveSvg.preview}
  static const String assetsImagesLiveSvg = 'assets/images/live.svg';

  /// {@macro assets_generator.assetsImagesLocationSvg.preview}
  static const String assetsImagesLocationSvg = 'assets/images/location.svg';

  /// {@macro assets_generator.assetsImagesLocationMarkSvg.preview}
  static const String assetsImagesLocationMarkSvg =
      'assets/images/location_mark.svg';

  /// {@macro assets_generator.assetsImagesLockSvg.preview}
  static const String assetsImagesLockSvg = 'assets/images/lock.svg';

  /// {@macro assets_generator.assetsImagesLogoPng.preview}
  static const String assetsImagesLogoPng = 'assets/images/logo.png';

  /// {@macro assets_generator.assetsImagesMessagePinSvg.preview}
  static const String assetsImagesMessagePinSvg =
      'assets/images/message_pin.svg';

  /// {@macro assets_generator.assetsImagesMessageRepresentativeSvg.preview}
  static const String assetsImagesMessageRepresentativeSvg =
      'assets/images/message_representative.svg';

  /// {@macro assets_generator.assetsImagesMessageSecretSvg.preview}
  static const String assetsImagesMessageSecretSvg =
      'assets/images/message_secret.svg';

  /// {@macro assets_generator.assetsImagesMessageTranscriptForwardSvg.preview}
  static const String assetsImagesMessageTranscriptForwardSvg =
      'assets/images/message_transcript_forward.svg';

  /// {@macro assets_generator.assetsImagesMicrophoneSvg.preview}
  static const String assetsImagesMicrophoneSvg =
      'assets/images/microphone.svg';

  /// {@macro assets_generator.assetsImagesMuteSvg.preview}
  static const String assetsImagesMuteSvg = 'assets/images/mute.svg';

  /// {@macro assets_generator.assetsImagesNextSvg.preview}
  static const String assetsImagesNextSvg = 'assets/images/next.svg';

  /// {@macro assets_generator.assetsImagesNoResultSvg.preview}
  static const String assetsImagesNoResultSvg = 'assets/images/no_result.svg';

  /// {@macro assets_generator.assetsImagesNotifyIconIco.preview}
  static const String assetsImagesNotifyIconIco =
      'assets/images/notify_icon.ico';

  /// {@macro assets_generator.assetsImagesPersonalStickerSvg.preview}
  static const String assetsImagesPersonalStickerSvg =
      'assets/images/personal_sticker.svg';

  /// {@macro assets_generator.assetsImagesPinSvg.preview}
  static const String assetsImagesPinSvg = 'assets/images/pin.svg';

  /// {@macro assets_generator.assetsImagesPinArrowSvg.preview}
  static const String assetsImagesPinArrowSvg = 'assets/images/pin_arrow.svg';

  /// {@macro assets_generator.assetsImagesPlaySvg.preview}
  static const String assetsImagesPlaySvg = 'assets/images/play.svg';

  /// {@macro assets_generator.assetsImagesPlayerPauseSvg.preview}
  static const String assetsImagesPlayerPauseSvg =
      'assets/images/player_pause.svg';

  /// {@macro assets_generator.assetsImagesPlayerPlaySvg.preview}
  static const String assetsImagesPlayerPlaySvg =
      'assets/images/player_play.svg';

  /// {@macro assets_generator.assetsImagesPostDetailSvg.preview}
  static const String assetsImagesPostDetailSvg =
      'assets/images/post_detail.svg';

  /// {@macro assets_generator.assetsImagesPrevSvg.preview}
  static const String assetsImagesPrevSvg = 'assets/images/prev.svg';

  /// {@macro assets_generator.assetsImagesProxySvg.preview}
  static const String assetsImagesProxySvg = 'assets/images/proxy.svg';

  /// {@macro assets_generator.assetsImagesReadSvg.preview}
  static const String assetsImagesReadSvg = 'assets/images/read.svg';

  /// {@macro assets_generator.assetsImagesRecallSvg.preview}
  static const String assetsImagesRecallSvg = 'assets/images/recall.svg';

  /// {@macro assets_generator.assetsImagesRecentStickerSvg.preview}
  static const String assetsImagesRecentStickerSvg =
      'assets/images/recent_sticker.svg';

  /// {@macro assets_generator.assetsImagesRecordPreviewPlaySvg.preview}
  static const String assetsImagesRecordPreviewPlaySvg =
      'assets/images/record_preview_play.svg';

  /// {@macro assets_generator.assetsImagesRecordPreviewStopSvg.preview}
  static const String assetsImagesRecordPreviewStopSvg =
      'assets/images/record_preview_stop.svg';

  /// {@macro assets_generator.assetsImagesRecordRetrySvg.preview}
  static const String assetsImagesRecordRetrySvg =
      'assets/images/record_retry.svg';

  /// {@macro assets_generator.assetsImagesRecordStopSvg.preview}
  static const String assetsImagesRecordStopSvg =
      'assets/images/record_stop.svg';

  /// {@macro assets_generator.assetsImagesRotatoSvg.preview}
  static const String assetsImagesRotatoSvg = 'assets/images/rotato.svg';

  /// {@macro assets_generator.assetsImagesSelectedSvg.preview}
  static const String assetsImagesSelectedSvg = 'assets/images/selected.svg';

  /// {@macro assets_generator.assetsImagesSentSvg.preview}
  static const String assetsImagesSentSvg = 'assets/images/sent.svg';

  /// {@macro assets_generator.assetsImagesSettingSvg.preview}
  static const String assetsImagesSettingSvg = 'assets/images/setting.svg';

  /// {@macro assets_generator.assetsImagesShareSvg.preview}
  static const String assetsImagesShareSvg = 'assets/images/share.svg';

  /// {@macro assets_generator.assetsImagesShieldSvg.preview}
  static const String assetsImagesShieldSvg = 'assets/images/shield.svg';

  /// {@macro assets_generator.assetsImagesSlideContactsSvg.preview}
  static const String assetsImagesSlideContactsSvg =
      'assets/images/slide_contacts.svg';

  /// {@macro assets_generator.assetsImagesSmallCloseSvg.preview}
  static const String assetsImagesSmallCloseSvg =
      'assets/images/small_close.svg';

  /// {@macro assets_generator.assetsImagesSnapshotDoneSvg.preview}
  static const String assetsImagesSnapshotDoneSvg =
      'assets/images/snapshot_done.svg';

  /// {@macro assets_generator.assetsImagesStickerSvg.preview}
  static const String assetsImagesStickerSvg = 'assets/images/sticker.svg';

  /// {@macro assets_generator.assetsImagesStickerGifSvg.preview}
  static const String assetsImagesStickerGifSvg =
      'assets/images/sticker_gif.svg';

  /// {@macro assets_generator.assetsImagesStickerStoreSvg.preview}
  static const String assetsImagesStickerStoreSvg =
      'assets/images/sticker_store.svg';

  /// {@macro assets_generator.assetsImagesStickerStoreRedDotSvg.preview}
  static const String assetsImagesStickerStoreRedDotSvg =
      'assets/images/sticker_store_red_dot.svg';

  /// {@macro assets_generator.assetsImagesStrangersSvg.preview}
  static const String assetsImagesStrangersSvg = 'assets/images/strangers.svg';

  /// {@macro assets_generator.assetsImagesSuccessfulSvg.preview}
  static const String assetsImagesSuccessfulSvg =
      'assets/images/successful.svg';

  /// {@macro assets_generator.assetsImagesTransferSvg.preview}
  static const String assetsImagesTransferSvg = 'assets/images/transfer.svg';

  /// {@macro assets_generator.assetsImagesTransferFromPhoneSvg.preview}
  static const String assetsImagesTransferFromPhoneSvg =
      'assets/images/transfer_from_phone.svg';

  /// {@macro assets_generator.assetsImagesTransferToPhoneSvg.preview}
  static const String assetsImagesTransferToPhoneSvg =
      'assets/images/transfer_to_phone.svg';

  /// {@macro assets_generator.assetsImagesTriangleWarningSvg.preview}
  static const String assetsImagesTriangleWarningSvg =
      'assets/images/triangle_warning.svg';

  /// {@macro assets_generator.assetsImagesUploadSvg.preview}
  static const String assetsImagesUploadSvg = 'assets/images/upload.svg';

  /// {@macro assets_generator.assetsImagesUserSearchSvg.preview}
  static const String assetsImagesUserSearchSvg =
      'assets/images/user_search.svg';

  /// {@macro assets_generator.assetsImagesVerifiedSvg.preview}
  static const String assetsImagesVerifiedSvg = 'assets/images/verified.svg';

  /// {@macro assets_generator.assetsImagesVideoSvg.preview}
  static const String assetsImagesVideoSvg = 'assets/images/video.svg';

  /// {@macro assets_generator.assetsImagesVideoCallSvg.preview}
  static const String assetsImagesVideoCallSvg = 'assets/images/video_call.svg';

  /// {@macro assets_generator.assetsImagesVideoMessageSvg.preview}
  static const String assetsImagesVideoMessageSvg =
      'assets/images/video_message.svg';

  /// {@macro assets_generator.assetsImagesWarningSvg.preview}
  static const String assetsImagesWarningSvg = 'assets/images/warning.svg';

  /// {@macro assets_generator.assetsImagesWebViewRefreshSvg.preview}
  static const String assetsImagesWebViewRefreshSvg =
      'assets/images/web_view_refresh.svg';

  /// {@macro assets_generator.assetsImagesZoomInSvg.preview}
  static const String assetsImagesZoomInSvg = 'assets/images/zoom_in.svg';

  /// {@macro assets_generator.assetsImagesZoomOutSvg.preview}
  static const String assetsImagesZoomOutSvg = 'assets/images/zoom_out.svg';
}
