import 'package:json_annotation/json_annotation.dart';

enum MessageCategory {
  @JsonValue('SIGNAL_KEY')
  signalKey,
  @JsonValue('SIGNAL_TEXT')
  signalText,
  @JsonValue('SIGNAL_IMAGE')
  signalImage,
  @JsonValue('SIGNAL_VIDEO')
  signalVideo,
  @JsonValue('SIGNAL_STICKER')
  signalSticker,
  @JsonValue('SIGNAL_DATA')
  signalData,
  @JsonValue('SIGNAL_CONTACT')
  signalContact,
  @JsonValue('SIGNAL_AUDIO')
  signalAudio,
  @JsonValue('SIGNAL_LIVE')
  signalLive,
  @JsonValue('SIGNAL_POST')
  signalPost,
  @JsonValue('SIGNAL_LOCATION')
  signalLocation,
  @JsonValue('PLAIN_TEXT')
  plainText,
  @JsonValue('PLAIN_IMAGE')
  plainImage,
  @JsonValue('PLAIN_VIDEO')
  plainVideo,
  @JsonValue('PLAIN_DATA')
  plainData,
  @JsonValue('PLAIN_STICKER')
  plainSticker,
  @JsonValue('PLAIN_CONTACT')
  plainContact,
  @JsonValue('PLAIN_AUDIO')
  plainAudio,
  @JsonValue('PLAIN_LIVE')
  plainLive,
  @JsonValue('PLAIN_POST')
  plainPost,
  @JsonValue('PLAIN_JSON')
  plainJson,
  @JsonValue('PLAIN_LOCATION')
  plainLocation,
  @JsonValue('MESSAGE_RECALL')
  messageRecall,
  @JsonValue('STRANGER')
  stranger,
  @JsonValue('SECRET')
  secret,
  @JsonValue('SYSTEM_CONVERSATION')
  systemConversation,
  @JsonValue('SYSTEM_USER')
  systemUser,
  @JsonValue('SYSTEM_CIRCLE')
  systemCircle,
  @JsonValue('SYSTEM_SESSION')
  systemSession,
  @JsonValue('SYSTEM_ACCOUNT_SNAPSHOT')
  systemAccountSnapshot,
  @JsonValue('APP_BUTTON_GROUP')
  appButtonGroup,
  @JsonValue('APP_CARD')
  appCard,
  @JsonValue('WEBRTC_AUDIO_OFFER')
  webrtcAudioOffer,
  @JsonValue('WEBRTC_AUDIO_ANSWER')
  webrtcAudioAnswer,
  @JsonValue('WEBRTC_ICE_CANDIDATE')
  webrtcIceCandidate,
  @JsonValue('WEBRTC_AUDIO_CANCEL')
  webrtcAudioCancel,
  @JsonValue('WEBRTC_AUDIO_DECLINE')
  webrtcAudioDecline,
  @JsonValue('WEBRTC_AUDIO_END')
  webrtcAudioEnd,
  @JsonValue('WEBRTC_AUDIO_BUSY')
  webrtcAudioBusy,
  @JsonValue('WEBRTC_AUDIO_FAILED')
  webrtcAudioFailed,
  @JsonValue('KRAKEN_INVITE')
  krakenInvite,
  @JsonValue('KRAKEN_PUBLISH')
  krakenPublish,
  @JsonValue('KRAKEN_SUBSCRIBE')
  krakenSubscribe,
  @JsonValue('KRAKEN_ANSWER')
  krakenAnswer,
  @JsonValue('KRAKEN_TRICKLE')
  krakenTrickle,
  @JsonValue('KRAKEN_END')
  krakenEnd,
  @JsonValue('KRAKEN_CANCEL')
  krakenCancel,
  @JsonValue('KRAKEN_DECLINE')
  krakenDecline,
  @JsonValue('KRAKEN_LIST')
  krakenList,
  @JsonValue('KRAKEN_RESTART')
  krakenRestart,
  @JsonValue('ENCRYPTED_TEXT')
  encryptedText,
  @JsonValue('ENCRYPTED_IMAGE')
  encryptedImage,
  @JsonValue('ENCRYPTED_VIDEO')
  encryptedVideo,
  @JsonValue('ENCRYPTED_STICKER')
  encryptedSticker,
  @JsonValue('ENCRYPTED_DATA')
  encryptedData,
  @JsonValue('ENCRYPTED_CONTACT')
  encryptedContact,
  @JsonValue('ENCRYPTED_AUDIO')
  encryptedAudio,
  @JsonValue('ENCRYPTED_LIVE')
  encryptedLive,
  @JsonValue('ENCRYPTED_POST')
  encryptedPost,
  @JsonValue('ENCRYPTED_LOCATION')
  encryptedLocation,
}
